version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - restore_cache:
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apk
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}