version: 2
jobs:
  test_debug:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - restore_cache:
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}
          
  build_unsigned_release:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - restore_cache:
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apk
      - save_cache:
          paths:
            - ~/.gradle
          key: cache-build_debug-{{ .Environment.CI_CACHE_VERSION }}
      - persist_to_workspace:
          root: ~/code
          paths: app/build/outputs/apk/release/
  
  push_to_hockeyapp:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: ~/code
      - run:
          name: Setup env
          command: chmod 001 ./deploy_dev.sh
      - run:
          name: Push APK on HockeyApp
          command: ./deploy_dev.sh
          
workflows:
  version: 2
  debug:
    jobs:
      - test_debug
      - build_unsigned_release:
          requires:
            - test_debug
      - push_to_hockeyapp:
          requires:
            - build_unsigned_release
          filters:
            branches:
              only: staging